name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies and build
      - run: |
          cd projeto-pets-react
          npm ci
          npm run build
      - name: Deploy to Firebase
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROJETO_PETS_CONEXAO_CANINA }}
          channelId: live
          projectId: projeto-pets-conexao-canina
          entryPoint: projeto-pets-react
